import React from "react";
import { redirect } from "next/navigation";
import { Metadata } from "next";

import OpenEnded from "@/components/OpenEnded";
import prisma from "@/lib/db";
import { getAuthSession } from "@/lib/nextauth";

type Props = {
  params: Promise<{
    gameId: string;
  }>;
};

// 1. DYNAMIC METADATA
// Automatically displays the specific quiz topic in the browser tab.
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { gameId } = await params;
  const game = await prisma.game.findUnique({
    where: { id: gameId },
    select: { topic: true },
  });

  return {
    title: game ? `Playing Open-Ended: ${game.topic} | Quizzzy` : "Open-Ended Quiz | Quizzzy",
    description: "Test your knowledge with open-ended fill-in-the-blank questions generated by AI.",
  };
}

const OpenEndedPage = async ({ params }: Props) => {
  const session = await getAuthSession();

  if (!session?.user) {
    redirect("/");
  }

  const { gameId } = await params;

  // 2. SECURITY FIX: Added userId verification to prevent IDOR vulnerabilities.
  // This ensures users can only play games that belong to their account.
  const game = await prisma.game.findFirst({
    where: {
      id: gameId,
      userId: session.user.id,
    },
    include: {
      questions: {
        select: {
          id: true,
          question: true,
          answer: true,
        },
      },
    },
  });

  // 3. SAFETY CHECKS: Redirect if game doesn't match type or has no questions.
  if (!game || game.gameType === "mcq" || game.questions.length === 0) {
    redirect("/quiz");
  }

  return (
    <div className="animate-in fade-in duration-500">
      <OpenEnded game={game} />
    </div>
  );
};

export default OpenEndedPage;